CREATE DATABASE PORTFOLIO;
SHOW DATABASES;

USE PORTFOLIO;

CREATE TABLE RECORDS(
	RECORD_ID INT,
    NAME VARCHAR(25) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL,
    MESSAGE VARCHAR(200), 
    PRIMARY KEY(RECORD_ID)
);